name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        python-version: [3.8, 3.9, 3.10.0]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r venv/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  lint:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Super-Linter
      uses: github/super-linter@v4.9.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERRORS: true
        VALIDATE_ALL_CODEBASE: false
